### ISSUE TITLE
Changes in BR2_Chapter_1 for humble

### ISSUE THREAD

**Issue by varunvenna** [fmrico/book_ros2#12]
**changes from foxy to humble in chapter 1:**
---

**set Apt repositories:**

```bash
sudo apt update && sudo apt install curl
sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg

echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null

sudo apt update
```

**ROS2 available software**

```bash
apt-cache search ros-humble
```

**Install ROS2 from binaries**

```bash
sudo apt update

sudo apt install ros-humble-desktop
```

**Activate ROS2**

```bash
source /opt/ros/humble/setup.bash
```

```bash
echo "source /opt/ros/humble/setup.bash" >> /.bashrc
```

**Create and fill**
```bash
cd ~
mkdir -p bookros2_ws/src
cd bookros2_ws/src
git clone https://github.com/fmrico/book_ros2.git
vcs import . < book_ros2/third_parties.repos
```
---

while importing third-party repos using vcs if you run into the error:

**Command 'vcs' not found**

we have to install vcs using the below command:
```bash
sudo apt install python3-vcstool
```
---
**install dependencies**:
```bash
sudo rosdep init
rosdep update
```
```bash
cd ~/bookros2_ws
rosdep install --from-paths src --ignore-src -r -y
```
---

while installing dependencies if you run into the error, 

**rosdep command is not found.**

then run the following command:
```bash
sudo apt install python3-bloom python3-rosdep -y
```
then initialize rosdep
```bash
sudo rosdep init
rosdep update
```
---
if you run into an error while running **rosdep init**:
try:
```bash
sudo apt update && sudo apt upgrade
```
if this does not solve then do the below steps:
* open hosts file:
```bash
sudo gedit /etc/hosts
```
* add this line to the end of the file:
```
151.101.84.133 raw.githubusercontent.com
```

* save and close, then run:
```bash
sudo rosdep init
rosdep update
```
---

no changes in __Build the workspace__, and __activate the user workspace__ sections (sourcing the workspace)

---

posting changes as an issue as asked in the LinkedIn post.

**Comment by fmrico** [comment]
Hi @varunvenna !! Maybe I could have explained myself better. My request was for corrections and typos. I already had updated to Humble. In any case, thank you for your effort. I will include you as a reviewer in the book.

**Comment by varunvenna** [comment]
> Hi @varunvenna !! Maybe I could have explained myself better. My request was for corrections and typos. I already had updated to Humble. In any case, thank you for your effort. I will include you as a reviewer in the book.

Ohh, my bad 😅.
Thank you.

**Comment by ntak17** [comment]
nice
