### ISSUE TITLE
Book order (Go with Amazon - currently discount)

### ISSUE THREAD

**Issue by Genozen** [fmrico/book_ros2#15]
Not really an issue, but I'm not sure where to put this.

If you are looking to buy the book, I would suggest going with Amazon as they have a discounted price right now.

I purchased from the Routledge website a physical copy of the book, it has now been more than 2 weeks and the tracking status still says in pre-shipping (they have not printed it yet).

**Comment by fmrico** [comment]
Maybe the reason is the printing of the revised book. You will probably get the new version updated to humble, and with some typos/errors fixed 🤔
