### ISSUE TITLE
Unable to build the workspace fully successfully

### ISSUE THREAD

**Issue by Iyanuoluwa007** [fmrico/book_ros2#18]
# Important!!!
- [X] I have checked that this issue/bug/fix/correction has not been already created before in open or closed issues.

# Type of bug
- [ ] A) Typo/error in Figure/text
- [X] B) Bug in code
- [ ] C) General comment, recommendation or petition 

# Issue Description
A clear and concise description of what the issue is (A, B, and C)

# B) *Bug Description*
(Remove section if not applicable)

## how to reproduce
2. Type on '....'
3. Execute '....'

## Expected behavior
a. Trying to use the vcstool as instructed in page 12
Instead im getting error: 
bash: book_ros2/thirld_parties.repos: No such file or directory

![Screenshot (133)](https://user-images.githubusercontent.com/70354778/233812833-417f84e5-ace8-4264-af1b-1f0296c79b0e.png)

b. Unable to build the workspace fully successfully, everything suppose to build successfully without any issue or any failure. As instructed on page 13.

## Desktop (please complete the following information):
 - OS: Ubuntu Focal

 - ROS2 Distro: Foxy

## Additional context

![Screenshot (130)](https://user-images.githubusercontent.com/70354778/233812607-54b0d226-38b5-4a0c-bbe4-b5a65abb7451.png)
![Screenshot (131)](https://user-images.githubusercontent.com/70354778/233812613-86b4ef64-dca0-4a8d-8c45-e8cd8dc3ba0e.png)
22.04]

**Comment by fmrico** [comment]
Several things happen here:

- Did you clone this repo in the src folder in your workspace. Then you should be finding third_parties.repos . It is there!
- Use the branch foxy-devel. In Humble, tf2_geometry_msgs  has .hpp; in Foxy is .h

I hope it helps

**Comment by Iyanuoluwa007** [comment]
Good day, Thanks for the swift response, I already have the third_parties.repos in the src folder already. Unfortunately, trying to perform the code "vcs import.<book ros2/third parties.repos" i got the error "No such file or directory".
![image](https://user-images.githubusercontent.com/70354778/234522803-a8fac119-7ed0-40b6-af05-b3e36430e7ef.png)

**Comment by fmrico** [comment]
The content that you shows in nautilus should be in a book_ros2 folder in src. I suppose you cloned the repo and then you moved the content to the src file...

**Comment by fmrico** [comment]
echo "source ~/bookros2_ws/install/setup.bash" >> ~/.bashrc
