### ISSUE TITLE
packages/stacks could not have their rosdep keys resolved to system dependencies

### ISSUE THREAD

**Issue by JaySlamer** [fmrico/book_ros2#2]
ubuntu 20.04 ROS foxy
![Screenshot from 2022-09-14 10-58-35](https://user-images.githubusercontent.com/12229227/190048801-0d38aa3a-c497-4a91-bb2c-a9c488144afb.png)

**Comment by fmrico** [comment]
Hi @JaySlamer 

As the book describes (available in a few days), use vcs to pull the repos in https://github.com/fmrico/book_ros2/blob/main/third_parties.repos .

![Captura de pantalla 2022-09-14 07:45:26](https://user-images.githubusercontent.com/3810011/190069540-11845b55-dac0-4907-809b-54796433434d.png)

Best
Francisco

**Comment by JaySlamer** [comment]
Thank you @fmrico , however third party packages had been pulled before I came cross this problem, I strictly followed the instructions step by step
![Screenshot from 2022-09-14 13-48-34](https://user-images.githubusercontent.com/12229227/190070062-17d05167-1b40-456e-a6ce-6d477d8a1f93.p
![Screenshot from 2022-09-14 13-48-41](https://user-images.githubusercontent.com/12229227/190070075-729ae7ca-70fa-4bbb-a22b-ce392aaa3904.png)
ng)

**Comment by fmrico** [comment]
Hi @JaySlamer 

What is your ROS2 distro? What branch are you using?  Did you get any errors building the workspace?

Best

**Comment by JaySlamer** [comment]
> 

I am using ros2 foxy and foxy-devel branch.  Yeah, errors related to google protobuf. May I ask what version of protobuf are you using? Mine is 3.14.x.
![Screenshot from 2022-09-15 09-37-33](https://user-images.githubusercontent.com/12229227/190293139-e1e9383c-1fba-4c89-9038-ac71931f2f06.png)

**Comment by joseugeMB** [comment]
Hi @JaySlamer ,
Probably is too late, but I just faced the same problem, so I'll post what worked for me in case it happens to anyone else. It seems that the problem is due to Foxy been an EOL distro. I tried:

$ rosdep update --include-eol-distros

Before doing:

$ rosdep install --from-paths src --ignore-src -r -y

That made all packages being found successfully.
Best regards

**Comment by fmrico** [comment]
Thanks @genimnb
