### ISSUE TITLE
update your fucking book

### ISSUE THREAD

**Issue by phil123456** [fmrico/book_ros2#24]
i@ubuntu:~/WORK/bookros2_ws$ colcon build --symlink-install
Starting >>> controller_manager_msgs
Starting >>> ros2_control_test_assets
Starting >>> launch_pal                                                                              
Starting >>> twist_mux                                                                                                   
Finished <<< ros2_control_test_assets [3.99s]                                                                                                     
Starting >>> hardware_interface                                                                                            
--- stderr: hardware_interface                                                                                                  
CMake Error at CMakeLists.txt:14 (find_package):
  By not providing "Findcontrol_msgs.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "control_msgs", but CMake did not find one.

  Could not find a package configuration file provided by "control_msgs" with
  any of the following names:

    control_msgsConfig.cmake
    control_msgs-config.cmake

  Add the installation prefix of "control_msgs" to CMAKE_PREFIX_PATH or set
  "control_msgs_DIR" to a directory containing one of the above files.  If
  "control_msgs" provides a separate development package or SDK, be sure it
  has been installed.

---
Failed   <<< hardware_interface [4.17s, exited with code 1]
Aborted  <<< twist_mux [9.27s]                                                                                                         
Aborted  <<< controller_manager_msgs [10.2s]                                                                    
Aborted  <<< launch_pal [10.7s]                        

Summary: 1 package finished [12.9s]
  1 package failed: hardware_interface
  3 packages aborted: controller_manager_msgs launch_pal twist_mux
  2 packages had stderr output: hardware_interface twist_mux
  52 packages not processed

**Comment by fmrico** [comment]
Dear @phil123456 

I have just checked that everything is building and running in Ubuntu 22.04 and ROS 2 Humble. Please check:
1. Are you using `Humble`? branch `main` points to Humble
2. Did you run `rosdep install --from-paths src --ignore-src -r -y`

In the case of  Ubuntu 20.04 and ROS 2 Foxy, I have detected some problems installing dependencies with `rosdep install --from-paths src --ignore-src -r -y`, so you will need to install it manually. Typically, if the missing package is `control_msgs`, the package to install is `ros-foxy-control-msgs` (adding ros-foxy and replacing `_` with `-`. From a fresh Foxy Full Desktop install, I had to install some packages manually by:

```
sudo apt install ros-foxy-desktop python3-argcomplete
sudo apt install ros-foxy-behaviortree-cpp-v3
sudo apt install ros-foxy-diagnostic-updater
sudo apt install ros-foxy-nav2-msgs
sudo apt install ros-foxy-control-msgs
sudo apt install ros-foxy-xacro
sudo apt install ros-foxy-vision-msgs
sudo apt install ros-foxy-realtime-tools 
sudo apt install ros-foxy-control-toolbox
sudo apt install ros-foxy-gazebo-dev 
sudo apt install ros-foxy-gazebo-ros
sudo apt install ros-foxy-joy-teleop
``` 

I am closing this issue. Please reopen if this problem persists.

Finally, please avoid rude language in the future. I completely understand your frustration, but this is not how to professionally work cordially with anyone. Please redirect your anger to productive and/or playful activities.

**Comment by Blueicaro** [comment]
Hello, I got the same problem. The problem was some missing packages. I install that packages manually as you said and now every think works nice
Thanks
