### ISSUE TITLE
failed to colcon build the book_ros2 package

### ISSUE THREAD

**Issue by AWAISADIS** [fmrico/book_ros2#26]
ok so basically i am following all the steps in yr book to build the package. successfully gitcloned the humble-devel branch, rosdep works fine too. problem comes in colcon build. it says that it can't find the cmake file specified and 33 packages don't get installed. here's the screenshot of this issue. it would be nice of you to look up this issue.
![Screenshot](https://github.com/fmrico/book_ros2/assets/104187957/edda84d0-5a29-4384-b03f-a3e28dfc8a28)

**Comment by fmrico** [comment]
It seems like your installation is incomplete. Check that you run:

`sudo apt install python3-colcon-common-extensions`

**Comment by fmrico** [comment]
Closing as there is no feedback. Reopen if needed

**Comment by phgandhi02** [comment]
I am getting the same error. I checked to where the cmake file is in the scripts directory of the ThirdParty directory; however, I couldn't find a cmake file only a .py file. I think this is where the error is showing up as only some of the directories have cmake files that can be autobuilt. Initially I tried running colcon build but I got the following: 
<img width="960" alt="image" src="https://github.com/fmrico/book_ros2/assets/127564266/79ee0d15-9943-4558-bdea-82c5a3a74a25">
So i used the export CMAKE_PREFIX_PATH( ~/bookros2_ws) to try and see if CMAKE could find any cmake files there. Afterwards, I got this error when I ran the colcon command again. The number of packages aborted has changed.
<img width="956" alt="image" src="https://github.com/fmrico/book_ros2/assets/127564266/cd433c62-7400-45bf-a694-113ab355b747">
<img width="960" alt="image" src="https://github.com/fmrico/book_ros2/assets/127564266/71aa05a4-3eb5-488a-a3bf-899687fe2cfa">

**Comment by phgandhi02** [comment]
Seems like this worked after I completed the my_package section. Though I'm not sure why. I still have stderr output on br2_fsm_bumgo_py and launch_pal

**Comment by fmrico** [comment]
That looks like you didn't sourced your underlay before building 🤔
