### ISSUE TITLE
br2_fsm_bumgo_cpp does not make Tiago move

### ISSUE THREAD

**Issue by npnquang** [fmrico/book_ros2#31]
# Important!!!
- [x] I have checked that this issue/bug/fix/correction has not been already created before in open or closed issues.

# Type of bug
- [ ] A) Typo/error in Figure/text
- [x] B) Bug in code
- [ ] C) General comment, recommendation or petition 

# Issue Description
When launching Tiago sim and br2_fsm_bumpgo_cpp Node, Tiago does not move despite the message is published to the topics `scan_raw` and `nav_vel`.

# B) *Bug Description*
I launched the Tiago and BumpGo node but Tiago does not move. I tried to change the RMW_IMPLEMENTATION to `rmw_cyclonedds_cpp`, echo the messages being published to the topics and even reclone the repo but nothing happens. When launching the Tiago sim, many warnings are displayed but I'm not sure if those warnings affect the nodes. I just started the book so I'm not sure where to debug this. Any help is much appreciated. Thank you.

## how to reproduce
1. Execute 'ros2 launch br2_tiago sim.launch.py'
2. Execute 'ros2 launch br2_fsm_bumpgo_cpp bump_and_go.launch.py'

## Expected behavior
Tiago robot moves around.

## Screenshots
This is the message published to `/scan_raw`
![image](https://github.com/fmrico/book_ros2/assets/73055557/d13fa215-6b9b-405d-ab20-310166e0cdc9)
This is the message published to `/nav_vel`
![image](https://github.com/fmrico/book_ros2/assets/73055557/00ba7659-0a39-4c12-9321-92600e7168f7)
This is the warnings when launching Tiago sim
![image](https://github.com/fmrico/book_ros2/assets/73055557/afae9124-4f93-4684-9386-e082c8001949)
![image](https://github.com/fmrico/book_ros2/assets/73055557/24ca7dcb-51ae-46f3-ba29-d1cac98a4450)
![image](https://github.com/fmrico/book_ros2/assets/73055557/5d7069df-8d7f-4848-8fab-807c04252502)
![image](https://github.com/fmrico/book_ros2/assets/73055557/2cd512c1-5ebf-4248-b39b-1d6c5602d8b6)
![image](https://github.com/fmrico/book_ros2/assets/73055557/31c7a0be-5908-44ba-ae91-ea34cc60515c)

## Desktop (please complete the following information):
 - OS: Ubuntu 22.04
 - ROS2 Distro: Humble

**Comment by zarak3268** [comment]
The bumpgo node publishes to `/output_vel`, which is mapped to `/nav_vel`. Change the mapping from `/output_vel -> /nav_vel` to `/output_vel -> /cmd_vel` should fix this. This repo was created 2 years ago so maybe back then the /nav_vel topic was used, but I did not find /nav_vel when I ran `ros2 topic list`, only `/cmd_vel`

**Comment by fmrico** [comment]
:thinking: What branch and ROS Distro are you using?

**Comment by Cristian-wp** [comment]
Hello Dott. @fmrico , I had the same problem in the master branch.
Changing the remapping as @zarak3268 said fix the problem.
