### ISSUE TITLE
Errors in building example packages under the book_ros2.git

### ISSUE THREAD

**Issue by HuiTinFat** [fmrico/book_ros2#32]
# Important!!!
- I have checked that this issue/bug/fix/correction has not been already created before in open or closed issues.

## Screenshot
Summary: 7 packages finished [19.8s]
  1 package failed: pal_gripper_description
  3 packages aborted: br2_tracking_msgs pal_gazebo_worlds pmb2_description
  2 packages had stderr output: launch_pal pal_gripper_description
  26 packages not processed

## Proposal
Advise how to fix or correct the issue

## Desktop (please complete the following information):
 - OS: Ubuntu 22.04
 - ROS2: Humble

**Comment by fmrico** [comment]
May you provide a screenshot of the error?

**Comment by HuiTinFat** [comment]
Official (Closed) - Sensitive Normal

Dear Francisco

I hope this message finds you well. I am currently following your book “Robot Programming with ROS2” and have encountered an issue on page 41 regarding the “Simulated Robot Setup” using the sim_launch.py.

When I try to launch the Tiago Robot, I receive the following error message:

“~/bookros2_ws/src/ThirdParty/tiago_simulation/tiago_gazebo is not a valid package name.”

I have carefully followed the instructions but seem to be stuck at this point. I would greatly appreciate it if you could investigate this problem or provide any guidance that might help me resolve this issue.

Thank you in advance for your assistance!

Best Regards

-Tin Fat

HUI Tin Fat | School of Engineering/RRIC
T: (65) 64606190
Ngee Ann Polytechnic, 535 Clementi Road, Singapore 599489
Visit us at http://www.np.edu.sg<http://www.np.edu.sg/>

***@***.******@***.******@***.******@***.******@***.***>***@***.******@***.***<https://www.youtube.com/NgeeAnnPolyNP>

**Comment by fmrico** [comment]
I think the people from PAL are migrating to Gazebo Ignition for Jazzy in the Humble-devel branch. I will investigate how to fix this...

**Comment by HuiTinFat** [comment]
Official (Closed) - Sensitive Normal

Noted with Thanks

**Comment by fmrico** [comment]
Hi @HuiTinFat . See #34
