### ISSUE TITLE
Impossible to use the actual repo with foxy

### ISSUE THREAD

**Issue by dottantgal** [fmrico/book_ros2#33]
Hello my friend,
I've got back the book trying to explain things to a friend using foxy, but its actually impossible to run everything cause a lot of dependencies to run tiago are not available anymore for foxy so, for ex, even if I'm able to build the ws i dont have the publishing of topic such as head_front_camera/rgb/image_raw and so on.
Please, try again to perform every single action described in your book using foxy and you'll see what is missed.

Anyway keep up the good work, thank you!

**Comment by fmrico** [comment]
Hi @dottantgal . See comment in #34
