### ISSUE TITLE
There are three examples in Chapter 6. The last example cannot be run.

### ISSUE THREAD

**Issue by kelejichi6463** [fmrico/book_ros2#34]
# Important!!!
- [✔] I have checked that this issue/bug/fix/correction has not been already created before in open or closed issues.

# Type of bug
- [ ] A) Typo/error in Figure/text
- [ ✔] B) Bug in code
- [ ] C) General comment, recommendation or petition 

# Issue Description
There are three examples in Chapter 6. The last example cannot be run.
Execute:
`ros2 launch br2_tiago sim.launch.py is_public_sim:=True
ros2 launch br2_navigation tiago_navigation.launch.py
rviz2 --ros-args -p use_sim_time:=true
ros2 launch br2_bt_patrolling patrolling.launch.py`
See error: 
But RViz failed to display the expected map information and prompted an error: "Global Status: Error"

## Screenshots
![image](https://github.com/user-attachments/assets/f593a7f8-d407-4584-aa38-b7a51cee2cac)
![image](https://github.com/user-attachments/assets/3a1ebc6a-3922-4a9a-be6d-e1b7fe2c915e)

## Desktop (please complete the following information):
 - OS:Ubuntu 22.04
 - ROS2 Humble

**Comment by fmrico** [comment]
Hi @kelejichi6463 

The book was published two years ago, and its target distribution is Foxy (Ubuntu 20.04), which has an End of Life date of June 20th, 2023. However, I have been updating the source code to Humble (Ubuntu 22.04) and recently to Jazzy (Ubuntu 24.04). Additionally, the repositories where the simulator is supported (managed by PAL Robotics) have evolved without my control, causing problems. 

I am preparing the second edition of the book, in which I will fork the PAL repositories to have more control and to prevent similar problems in the future. This new edition will be ready in a couple of months, and I will ensure that all the projects are compatible with Jazzy and the new Gazebo simulator. I appreciate your patience, and I recommend trying it on Jazzy once it's ready. Additionally, I am considering preserving the versions of the first edition and placing them in a docker to ensure that everything works correctly.

Best

**Comment by kelejichi6463** [comment]
Dear Professor fmrico,
I hope this email finds you well. I am a beginner in ROS2, and through your book, I have been able to gain a foundational understanding of its use. I believe your book is the best teaching material on ROS2 available on Amazon.
Thank you very much for your invaluable work. I look forward to your next book.
Best regards
