### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by jwson97** [fmrico/book_ros2#9]
# Type of bug
- [O ] A) Typo/error in Figure/text
- [] B) Bug in code
- [ ] C) General comment, recommendation or petition 

# Issue Description
Fail to build
$ colcon build --symlink-install
I got building error

# A) *Typo/Error Description*
(Remove section if not applicable)

## Screenshot
If applicable, add screenshots to help explain the problem.
![image](https://user-images.githubusercontent.com/42993434/201863687-1e246880-882a-4233-9b3d-c9a41f0f28b6.png)

## how to reproduce
1. cd ~
2. mkdir -p bookros2_ws/src
3. cd bookros2_ws/src
4. git clone https://github.com/fmrico/book_ros2.git
5. vcs import . < book_ros2/third_parties.repos
6. cd ..
7. rosdep install --from-paths src --ignore-src -r -y
8. colcon build --symlink-install

## Expected behavior
Building success

## Desktop (please complete the following information):
 - OS: [e.g. Ubuntu 22.04]
 - ROS2 Distro [e.g. Foxy, Humble]

**Comment by jwson97** [comment]
I solved this with humble-devel branch.

**Comment by fmrico** [comment]
Hi @jwson97 

I don't know why Groot got confused with your ROS version :thinking: It was trying to compile as a ROS 1 package.

It is closing as it is resolved.
